version: '3.5'
services:
  na-ts:
    image: 'bitnami/nats:latest'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
       - ~/na/nats.conf:/opt/bitnami/nats/nats-server.conf
       - ~/na/nats:/bitnami/nats:rw
networks:
  default:
    external:
      name: picky
