version: '3.5'
services:
  na-ts:
    image: 'bitnami/nats:latest'
    user: "$UID:$GID"
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
       - ~/na/nats.conf:/bitnami/nats/conf/nats-server.conf:ro
       - ~/na/nats:/bitnami/nats:rw
networks:
  default:
    external:
      name: picky
